# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuCreate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('MenuID', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='menuCreate.MenuCreateModel')),
            ],
        ),
    ]
