# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuResponse', '0003_auto_20190313_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuresponsemodel',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
        migrations.AlterField(
            model_name='menuresponsemodel',
            name='userName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
